CryptAByte.WebUI/Controllers/SelfDestructController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using CryptAByte.CryptoLibrary.CryptoProviders;
using CryptAByte.Domain.DataContext;
using CryptAByte.Domain.KeyManager;
using CryptAByte.Domain.SelfDestructingMessaging;
using CryptAByte.WebUI.Models;
using Ionic.Zip;

namespace CryptAByte.WebUI.Controllers
{
    public class SelfDestructController : Controller
    {
        private readonly ISelfDestructingMessageRepository selfDestructingMessageRepository;

        public SelfDestructController(ISelfDestructingMessageRepository selfDestructingMessageRepository)
        {
            this.selfDestructingMessageRepository = selfDestructingMessageRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Send(SelfDestructingMessageModel message)
        {
            // verify email

            if (!Domain.Validation.IsValidEmail(message.Email))
            {
                throw new ArgumentException("email", "invalid email format");
            }


            string passphrase = PronounceablePasswordGenerator.Generate(32);

            passphrase = HttpUtility.UrlEncode(passphrase);

            int messageId = selfDestructingMessageRepository.StoreMessage(new SelfDestructingMessage()
            {
                Message = message.MessageText
            },
            passphrase,
            message.AttachmentName,
            message.Attachment);

            string hash = SymmetricCryptoProvider.GetSecureHashForString(message.MessageText);

            const string notification = @"
Hello,

You have received a self-destructing message.  This message will be decrypted and erased when you open the link below.

You can read it at 

https://{0}:{1}/selfdestruct/read/?messageId={2}&passphrase={3}&hash={4}


CryptAByte.com is not responsible for the contents of messages.  For more information, please visit https://CryptAByte.com/SelfDestruct
";

            MailMessage mailMessage = new MailMessage { From = new MailAddress("webmaster@cryptabyte.com") };
            mailMessage.To.Add(new MailAddress(message.Email));

            mailMessage.Subject = "New self-destructing message @ CryptAByte";

            if (Request == null)
            {
                string messageText = string.Format(notification, "cryptabyte.com", 443, messageId, passphrase, hash);

                Debug.WriteLine(messageText);

                mailMessage.Body = messageText;
            }
            else
            {
                mailMessage.Body = string.Format(notification, Request.Url.Host, Request.Url.Port, messageId, passphrase, hash); ;
            }

            SmtpClient client = new SmtpClient();
            client.Send(mailMessage);

            return Content("Message sent");
        }

        public ActionResult Read(int messageId, string passphrase, string hash)
        {
            var model = new SelfDestructingMessageModel();

            try
            {
                var message = selfDestructingMessageRepository.GetMessage(messageId, passphrase);

                string originalHash = SymmetricCryptoProvider.GetSecureHashForString(message.Message);

                if (hash != originalHash)
                {
                    model.MessageText = "Error: hash of retrieved message does not match the original message hash." + Environment.NewLine +
                        "The message may have been tampered with!";
                    model.InvalidMessageId = true;
                    return View("Read", model);
                }

                // File Attachments
                if (message.HasAttachment)
                {
                    Message attachment = new Message { EncryptionKey = passphrase, MessageId = message.MessageId };
                    StoreEncryptedFileInTemporaryMemory(attachment);

                    model.HasAttachment = true;
                    model.TemporaryDownloadId = attachment.TemporaryDownloadId;
                    //model.AttachmentName = message.AttachmentName;
                }
                else
                {
                    model.HasAttachment = false;
                }

                model.MessageText = message.Message;
            }
            catch (Exception ex)
            {
                model.InvalidMessageId = true;
                model.MessageText = ex.Message;
            }

            return View("Read", model);
        }

        public ActionResult GetAttachment(string fileId)
        {
            var key = HomeController.FilePasswords.FirstOrDefault(p => p.Key == fileId && p.Value.Expires > DateTime.Now).Value;

            if (key == null)
            {
                Response.StatusCode = 500;
                return Content("Temporary password has expired.  Close this popup and re-enter your password.");
            }

            try
            {

                SelfDestructingMessageAttachment attachment = selfDestructingMessageRepository.GetAttachment(key.MessageId, key.Passphrase);

                if (attachment == null)
                {
                    Response.StatusCode = 500;
                    return Content("File not found. It may have been already downloaded");
                }

                //string decryptedString = new SymmetricCryptoProvider().DecryptWithKey(attachment.Attachment, key.Passphrase);
                byte[] decryptedArray = Convert.FromBase64String(attachment.Attachment);

                var zipStream = new MemoryStream(decryptedArray);
                var outputFileStream = new MemoryStream();

                using (ZipFile zip = ZipFile.Read(zipStream))
                {
                    zip.First().Extract(outputFileStream);
                    Response.AppendHeader("Content-Disposition", "attachment; filename=" + zip.First().FileName);
                }

                Response.ContentType = "application/octet-stream";
                outputFileStream.Seek(0, SeekOrigin.Begin);
                return new FileStreamResult(outputFileStream, "application/zip");

            }
            catch (ArgumentNullException ex)
            {
                Response.StatusCode = 500;
                return Content("File does not exist.  Was it already downloaded?");
            }
        }


        private static void StoreEncryptedFileInTemporaryMemory(Message message)
        {
            message.TemporaryDownloadId =
                SymmetricCryptoProvider.GenerateKeyPhrase(64);

            HomeController.FilePasswords.Add(message.TemporaryDownloadId,
                              new TemporaryDownloadKey
                              {
                                  Expires = DateTime.Now.AddSeconds(HomeController.PasswordExpiresInSeconds),
                                  MessageId = message.MessageId,
                                  Passphrase = message.EncryptionKey
                              });


        }


    }
}

CryptAByte.WebUI/Views/SelfDestruct/Index.cshtml
@model CryptAByte.WebUI.Models.SelfDestructingMessageModel
@{
    Page.Title = "Self-Destructing Messaging: encrypted emails which auto-delete after being read; share secrets anonymously";
}

<h1>Self-Destructing Messaging</h1>
@*<h3 class="red-box error">Warning: this service is currently under a testing
    period.  Please
    don't use it for
    anything important.</h3>*@

<h3>Self-destructing messages are messages that erase themselves after the recipient
    reads them.</h3>
<div>
    <strong>Here is how it works:</strong>
    <ol>
        <li>Write your message and enter the email address of the recipient.</li>
        <li>The message is encrypted with a random passphrase and stored on the server.  The
            passphrase
                is embedded in the link to open the message.</li>
        <li>When the recipient clicks on the link, this website decrypts the message and in
            the same step, erases the message.</li>
    </ol>
</div>



@Html.Partial("Send")

<div class="ui-accordion">

    <h3><a href="#">Notes</a></h3>
    <div>

        <ul>
            <li>The passphrase is not stored and the message is never stored in decrypted form,
                so it is impossible for the administrator
                to reveal the message after it is sent.</li>
            <li>If other than the intended recipient opens the email before it is read, they will
                be able to read the
                message.  The intended recipient will know that the email was read because the message
                will no longer be available.</li>
            <li>The read URL contains a hash of the original message.  This is used to verify that
                the message has not changed since it was sent -- as might happen if the database
                used to store the messages was hacked or compromised.</li>
        </ul>

    </div>

    <h3><a href="#">Cautions &amp; Disclaimers</a></h3>
    <div>

        <ul>
            <li>It may be possible for force the operator
                of the website
                (either by a lawful court order or by compromising our security) to reveal the
            message
                without notifying the original recipient if the sent email is available - for example,
                if someone has access the inbox of the recipient.  (<a href="http://blog.cryptabyte.com/2013/09/10/cryptabyte-responds-secret-fisa-letters-nsa-spying/">Read More</a>)   </li>
            <li>If you wish to recieve information securily and anonymously, we suggest you use
                CryptAByte's messaging service.  If you wish to anonymously share information and
                understand the risks involved,
                you can use this service.</li>
            <li>We may store the sender's IP address and recipient email address to prevent abuse
                of this service.  The mail server itself may also keep a record of the recipients
                email address and a temporary copy of the read URL (containing the passphrase) itself
                while
                it is being sent.
            </li>
        </ul>

    </div>



</div>

CryptAByte.WebUI/Views/SelfDestruct/Read.cshtml
@using CryptAByte.WebUI.Controllers
@model CryptAByte.WebUI.Models.SelfDestructingMessageModel
@{
    ViewBag.Title = "Self-Destructing Messaging";  
}

<h1>Self-Destructing Messaging</h1>

<h2 class="error">Note: the decrypted message below has been erased and can no longer
    be retrieved
    from this URL.</h2>

@if (!Model.InvalidMessageId)
{
    <div class="grey-box">
        @Model.MessageText
    </div>    
    
    if (Model.HasAttachment)
    {
    <h3>Download attachment:</h3> 
    <h4><a href="#" onclick="javascript:GetAttachment('@Model.TemporaryDownloadId');">Download
                Attached File @Model.AttachmentName</a></h4>
    
    <p class="red-box">
        <em>Note: The secure link above is valid for @HomeController.PasswordExpiresInSeconds seconds,
             after which file will be permanently removed! </em>
    </p>
    
    }


}
else
{
    <h2 class="error">
        @Model.MessageText
    </h2>
}

CryptAByte.WebUI/Views/SelfDestruct/Send.cshtml
@model CryptAByte.WebUI.Models.SelfDestructingMessageModel

<div id="SendMessageResult"></div>

<script type="text/javascript">

    function OnBegin() {
        $('#SendButton span').text('Sending...');
        $('#SendButton').fadeOut(3000);
    }

    function OnComplete() {
        $('#SendButton span').text('Send Message');
        $('#SendButton').fadeIn();
    }
</script>

<div class="blue-box">
    
<h3>Send a message:</h3>    

    @using (Ajax.BeginForm("Send", "SelfDestruct", new AjaxOptions() { OnBegin = "OnBegin", OnComplete = "OnComplete", OnSuccess = "OnSendMessage", UpdateTargetId = "MessageResult", OnFailure = "OnError" }))
    {
        <div>
            @Html.LabelFor(m => m.Email)
            @Html.EditorFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>
        <div>
            @Html.LabelFor(m => m.MessageText)
            <br />
            @Html.TextAreaFor(m => m.MessageText, new { style = "width:90%; horiz-align:center;", rows=10 })
            @Html.ValidationMessageFor(m => m.MessageText)
        </div>
        <button class="ui-button" id="SendButton">
            Send Message
        </button>
    
    }
</div>