CryptAByte.WebUI/Controllers/KeyServiceController.cs
using System;
using System.Collections.Generic;
using System.Web.Helpers;
using System.Web.Mvc;
using CryptAByte.Domain.KeyManager;
using CryptAByte.Domain.SelfDestructingMessaging;
using CryptAByte.WebUI.Models;

namespace CryptAByte.WebUI.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IRequestRepository requestRepository;
        private readonly ISelfDestructingMessageRepository selfDestructingMessageRepository;

        public ServiceController(IRequestRepository requestRepository, ISelfDestructingMessageRepository selfDestructingMessageRepository)
        {
            this.requestRepository = requestRepository;
            this.selfDestructingMessageRepository = selfDestructingMessageRepository;
        }

        [ValidateInput(false)]
        public ActionResult Index(string passphrase = null, string publickey = null, string privatekey = null, string privatekeyhash = null, string token = null, string message = null, string encryptedmessage = null, string encryptionkey = null)
        {
            #region Optionally - send sensitive parameters in request header

            if (Request.Headers["publickey"] != null)
            {
                token = Request.Headers["publickey"];
            }

            if (Request.Headers["privatekey"] != null)
            {
                token = Request.Headers["privatekey"];
            }

            if (Request.Headers["token"] != null)
            {
                token = Request.Headers["token"];
            }

            if (Request.Headers["passphrase"] != null)
            {
                passphrase = Request.Headers["passphrase"];
            }

            #endregion Optionally - send parameters in request header

            if (Request.HttpMethod == "GET" && token != null)
            {
                return GetMessages(token, passphrase, privatekeyhash);
            }
            if (Request.HttpMethod == "POST") // Create Key
            {
                return Create(passphrase, publickey, privatekey);
            }
            if (Request.HttpMethod == "PUT") // Send Message
            {
                return SendMessage(token, message, encryptedmessage, encryptionkey);
            }
            if (Request.HttpMethod == "DELETE") // Delete Token
            {
                return DeleteKey(token, passphrase);
            }
            return View();
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(string passphrase = null, string publickey = null, string privatekey = null, string privatekeyhash = null, DateTime? releasedate = null)
        {
            if (string.IsNullOrWhiteSpace(passphrase) && string.IsNullOrWhiteSpace(publickey))
            {
                Response.StatusCode = 400;
                // Response.Status = "MissingPassphraseOrPublicKey";
                return SerializeResult("Either a passphrase or a publickey parameter is required");
            }

            if (!string.IsNullOrWhiteSpace(publickey) && string.IsNullOrWhiteSpace(privatekey))
            {
                Response.StatusCode = 400;
                return SerializeResult("When sneding the public key, you must also send the privatekeyhash");
            }

            CryptoKey key = !string.IsNullOrWhiteSpace(passphrase)
                                ? CryptoKey.CreateRequestWithPassPhrase(passphrase)
                                : CryptoKey.CreateRequestWithPublicKey(publickey, privatekey, true, privatekeyhash);

            if (releasedate != null)
            {
                key.ReleaseDate = (DateTime)releasedate;
            }

            requestRepository.AddRequest(key);

            return SerializeResult(key);
        }



        //http://localhost:62633/Service/Get?token=a073f62e-e2de-48b9-8002-ac5994528038
        public ActionResult GetToken(string token)
        {
            var request = requestRepository.GetRequest(token);

            return SerializeResult(request);
        }

        // http://localhost:62633/Service/AddMessage?token=a073f62e-e2de-48b9-8002-ac5994528038&message=hello world
        //[HttpPost]
        public ActionResult SendMessage(string token, string message, string encryptedmessage, string encryptionkey)
        {
            if (Request.Files.Count == 0 && string.IsNullOrWhiteSpace(message) && string.IsNullOrWhiteSpace(encryptedmessage))
            {
                Response.StatusCode = 400;
                return SerializeResult("Message or encryptedmessage or file required");
            }

            if (Request.Files.Count > 0)
            {
                var uploadFile = Request.Files[0];

                byte[] fileData = RequestRepository.ReadFully(uploadFile.InputStream);
                requestRepository.AttachFileToRequest(token, fileData, uploadFile.FileName);
            }

            if (!string.IsNullOrWhiteSpace(message))
            {
                requestRepository.AttachMessageToRequest(token, message);
            }

            if (!string.IsNullOrWhiteSpace(encryptedmessage))
            {
                requestRepository.AttachEncryptedMessageToRequest(token, encryptedmessage, encryptionkey);
            }

            return SerializeResult(true);
        }

        // http://localhost:62633/Service/AddMessage?token=a073f62e-e2de-48b9-8002-ac5994528038&message=hello world
        //[HttpPost]
        public ActionResult GetMessages(string token, string passphrase, string privatekeyhash)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                Response.StatusCode = 400;
                //  Response.Status = "MissingToken";
                return SerializeResult("token is required");

            }

            if (string.IsNullOrWhiteSpace(passphrase) && string.IsNullOrWhiteSpace(privatekeyhash))
            {
                Response.StatusCode = 400;
                //  Response.Status = "MissingPassphrase";
                return SerializeResult("passphrase is required");
            }

            try
            {
                if (string.IsNullOrWhiteSpace(passphrase))
                {
                    var messages = requestRepository.GetDecryptedMessagesWithPassphrase(token, passphrase);

                    HomeController.StoreEncryptionKeysInApplicationMemory(messages);

                    if (messages == null || messages.Count == 0)
                    {
                        Response.StatusCode = 304; // not modified
                        return SerializeResult(new List<Message>());

                    }
                    return SerializeResult(messages);
                }
                else
                {
                    // return messages
                    var messages = requestRepository.GetEncryptedMessages(token, privatekeyhash);
                    return SerializeResult(messages);
                }
            }
            catch (ArgumentOutOfRangeException ex)
            {
                Response.StatusCode = 404;
                return SerializeResult(new { ex.Message });
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return SerializeResult("Server error decrypting messages.");
            }

        }


        #region Self-Destructing Messages

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult SelfDestruct()
        {
            Response.StatusCode = 400;
            return SerializeResult("POST to this URL with message and email");
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SelfDestruct(string message, string email, string attachment = null, string attachmentName = null)
        {

            if (string.IsNullOrWhiteSpace(message) || string.IsNullOrWhiteSpace(email))
            {
                Response.StatusCode = 400;
                return SerializeResult("message and email required");
            }

            try
            {
                byte[] attachmentData = new byte[] {};
                if (attachment != null)
                {
                    attachmentData = Convert.FromBase64String(attachment);
                }
                ContentResult result = new SelfDestructController(selfDestructingMessageRepository).Send(new SelfDestructingMessageModel() { Email = email, MessageText = message, Attachment = attachmentData, AttachmentName = attachmentName }) as ContentResult;

                return SerializeResult(result.Content == "Message sent");
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return SerializeResult(ex.Message);
            }

        }

        #endregion Self-Destructing Messages


        #region Private Helpers

        private ActionResult DeleteKey(string token = null, string passphrase = null)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                Response.StatusCode = 400;
                return SerializeResult("token is required");

            }

            if (string.IsNullOrWhiteSpace(passphrase))
            {
                Response.StatusCode = 400;
                return SerializeResult("passphrase is required");
            }

            try
            {
                requestRepository.DeleteKeyWithPassphrase(token, passphrase);

                return SerializeResult("Deleted.");
            }
            catch (ArgumentOutOfRangeException ex)
            {
                Response.StatusCode = 400;
                return SerializeResult(ex.Message);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return SerializeResult("Unable to delete key.");
            }
        }

        private ActionResult SerializeResult(object result)
        {

CryptAByte.WebUI/Views/Home/About-Apps.cshtml
@model dynamic
@{
    ViewBag.Title = "Desktop Apps";
   
}

<h2>Desktop Apps</h2>


<p>
    Windows/Mac desktop apps are still in progress. A test version (you can send messages but not files) is available for Windows <a
        href="https://cryptabyte.com/Content/CryptAByte.zip" title="Download">here</a>.
</p>

<p>
    <a href="https://github.com/DavidVeksler/CryptAByte">You can build this project yourself from the GitHub repository.</a>
</p>

<p>
    Please subscribe or follow the <a href="https://www.facebook.com/CryptAByte">Facebook
        page</a> for the latest update.
</p>


<img src="https://cryptabyte.com/Content/WinClient.png" />

CryptAByte.WebUI/Views/Home/About-Home.cshtml
@{
    Layout = null;
}
<div class="ui-accordion">
    <h3>
        <a href="#">About CryptAByte</a></h3>
    <div>
        <p>
            <strong>CryptAByte.com is a free online drop box that enables secure (encrypted) message
                and file sharing over the web using a public-key infrastructure. </strong>
        </p>
        <p>
            Messages and files are encrypted using a public key and can only be decrypted using
            the passphrase entered when your key is created. <strong>Your data is never stored in
                                                                 plaintext, and is impossible to decrypt without your passphrase.</strong>
        </p>
        <p>Get the Windows/Mac desktop <a href="/Home/Apps">apps here</a>.  Subscribe below to get updates.
        </p>
        
        <p>Would you like to run a copy of CryptAByte on your own website or private Intranet?  <a href="https://cryptabyte.com/Home/Contact">Contact us for a quote!</a>
        </p>
    </div>
    
   

    <h3>
        <a href="#">Why Use CryptAByte?</a></h3>
    <div>
        <p>
            Crypt-A-Byte uses public-key encryption just like HTTPS/SSL and OpenPGP/PGP. We
            encourage you to use <a href="http://dotmac.rationalmind.net/2012/06/notes-talk-information-security-fundamentals/">
                                     these tools</a> whenever possible.
        </p>
        <p>
            However, PGP requires that you and your recipient install and configure encryption
            software and create and exchange key pairs. When this is not practical, we make
            it very simple (and free) to share data using the same algorithms over the web.
        </p>
        <p>
            We use RSA for key pairs, encrypt messages and files using AES 256, and SHA256 for
            hashing.
        </p>
    </div>
    
      <h3>
        <a href="#">Subscribe</a></h3>
    <div>
        <p>Subscribe below and/or "like" the <a href="https://www.facebook.com/CryptAByte">Facebook page</a> to receive updates on new features.</p>
        @Html.Partial("Subscribe")
    </div>

    <h3>
        <a href="#">Disclaimer</a></h3>
    <div>
        <p>
            Keys (and messages) may be deleted 30 days after the lock date. The default lock
            date (customize in the advanced option of the create key dialog) is 30 days from
            the key creation date.
        </p>
        <p>
            This service is completely anonymous and keeps no user-specific records. It is impossible
            to decrypt your data without the passphrase you provide when a key is created. Furthermore,
            we do not record IP addresses or any other user-specific information.
            
            We do have access to your key at the moment you enter it, and may be forced to record
            your passphrase under a court order. (<a href="http://blog.cryptabyte.com/2013/09/10/cryptabyte-responds-secret-fisa-letters-nsa-spying/">Read more</a>)
            <br />
            To eliminate this risk, we encourage you to use our @Html.ActionLink("API", "Index", "Service")
            or the open-source offline app for Windows/Mac (coming soon) to access your data.
        </p>
    </div>

   

    <h3>
        <a href="#">Usage Scenarios</a></h3>
    <div>
        <p>
            <strong>Basic Scenarios:</strong>
        </p>
        <ul>
            <li>Secure messaging</li>
            <li>Secure file sharing</li>
            <li>Secure chat client</li>
            <li>Offline message support</li>
            <li>Secure email client</li>
        </ul>
        <p>
            <strong>Advanced Scenarios:</strong>
            <br />
            <em>When using the "release date" option (available via UI and API) messages can be
                delivered, but cannot be retrieved before a certain time.</em>
        </p>
        <ul>
            <li>Placing bets: each participant enters their guess at the public URL, but the answer
                cannot be seen until the release date.</li>
            <li>More to come...</li>
        </ul>
    </div>
    <h3>
        <a href="#">Terms &amp; Conditions</a></h3>
    <div>
        <p>
            Remember that as long as your keep your passphrase secret, it is impossible
            for anyone else to know what you use this
            service for. However if you publicly disclose your passphrase and anyone complains,
            we'll just delete your key (and thus any messages/files sent to it).
        </p>
        <p>
            <strong>Intellectual Property Complaints: </strong>If you object to any information
            being stored
            on this site, please send us the Key Id <em>and passphrase </em>via the contact
            page.
        </p>
    </div>


</div>

CryptAByte.WebUI/Views/Home/About.cshtml
@{
    //   ViewBag.Title = "Time-Lock： Do Not Decrypt Until ___";

    Page.Title = "About Crypt-A-Byte";
}

<h2>About</h2>

<div>
    <p>
        <strong>Crypt-A-Byte is a set of services offering secure communications on the web.
            It can
            be used via the web interface or via the API.  </strong>
    </p>

    <p>
        Would you like to run a copy of CryptAByte on your website or private Intranet?
        <a href="https://cryptabyte.com/Home/Contact">Contact us for a quote!</a>

        <a href="https://github.com/DavidVeksler/CryptAByte">GitHub repository.</a>
</div>




@Html.Partial("About-Home")

@*<h2>@ViewBag.Message</h2>
<p>
    Time-Lock： Do Not Decrypt Until ___
</p>
<p>
    <a href="/Home/RequestKeys">Request Keys</a> | 
</p>
<p>
    Time-Lock provides several ways to keep a secret until a certain time is reached
    and/or a certain person(s) agree to release it.
</p>
<p>
    There are many good tools for sharing password-protected information, but if you
    want to releval a secret based on certain criteria such as time or group consensus,
    you must rely on a trusted third party. Time-Lock allows you to define a set of
    conditions to handle many different situations
</p>
<p>
    Time-Lock can be used in a way that does not require you to trust it with your secret.
    You can use the Time-Lock site directly, or you can interface with its API from
    another application or website.
</p>
<p>
    Here are some ways that you can use Time-Lock:
</p>
<ol>
    <li>Record a secret today and don't reveal it until 7 minutes (or days or years) from
        now. The secret can automatically be send to a recipient after a certain time or
        deleted if it is not retrieved.</li>
    <li>You want to reveal a secret to a friend based on certain criteria which a referee
        will decide on. You can record the secret with Time-Lock and send the unlock key
        to the judge and the access key to your friend. The referee can unlock the secret
        with his key, but he will not be able to read the message. After the referee uses
        his unlock key, your friend will able to use his access key to read it.</li>
    <li>You want to leave a message for three friends which requires all three to enter
        their password to open it.</li>
    <li>Same as scenario 1, but requires sufficient calculations to ensure that your secret
        can be kept whether or not you trust Time-Lock and even if the website is not available.
    </li>
</ol>
<ol>
    <li>Trusted Third Party</li>
    <li>Mutual Friend</li>
    <li>Consensus</li>
    <li>Pre-Calculate key</li>
</ol>
<p>
    <strong>Sources:</strong>
    <ul>
        <li>http://www.gwern.net/Self-decrypting%20files</li>
        <li>https://bcrypt.codeplex.com/</li>
        <li></li>
    </ul>
</p>
*@

CryptAByte.WebUI/Views/Home/Contact.cshtml
@model CryptAByte.WebUI.Models.ContactFormModel 
@{
    ViewBag.Title = "Contact Us";
}

<h2>Contact Us/Submit Feedback</h2>

@using (Ajax.BeginForm("SubmitContact", "Home", new AjaxOptions() { OnSuccess = "ShowMessageSent", OnFailure = "OnError" }))
{

    <div>

        <div>
            @Html.LabelFor(m => m.Name)
            @Html.EditorFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <div>
            @Html.LabelFor(m => m.Email)
            @Html.EditorFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>
        <div>
            @Html.LabelFor(m => m.Message)
            <br />
            @Html.TextAreaFor(m => m.Message, new { rows = 10, cols = 100 })
            @Html.ValidationMessageFor(m => m.Message)
        </div>

        <button class="ui-button">Send</button>


    </div>

}

CryptAByte.WebUI/Views/Home/CreateKey.cshtml
@{ Layout = null;}
@model CryptAByte.WebUI.Models.NewKeyModel
@using (Ajax.BeginForm("CreateKey", "Home", new AjaxOptions() { OnSuccess = "ShowKeyDetailWindow", UpdateTargetId = "KeyDetails", OnFailure = "OnError" }))
{

    <div id="KeyDetails"></div>
    
    <div id="CreateKey" class="grey-box">
        <h2>1: Get a Key Id</h2>

        <ul style="width: 400px">
            <li>A "Key Id" is a unique URL which points to a mailbox that accepts encrypted messages.
            </li>
            <li>Only those who know the passphrase will be able to retrieve the message sent to
                the Key Id.</li>
            <li>We recommend you leave the passphrase field blank to generate a strong, random passphrase.
            </li>
        </ul>


        <div>@Html.LabelFor(m => m.Passphrase)
            @Html.EditorFor(m => m.Passphrase)
            @Html.ValidationMessageFor(m => m.Passphrase)
        </div>
        <div id="AdvancedOptions" style="display: none; margin: 10px;">
            <fieldset>
                <legend>Advanced Options</legend>
                <div>
                    @Html.CheckBoxFor(m => m.DeleteMessagesAfterReading)
                    @Html.LabelFor(m => m.DeleteMessagesAfterReading)
                </div>
                <div>
                    @Html.CheckBoxFor(m => m.DeleteKeyAfterReading)
                    @Html.LabelFor(m => m.DeleteKeyAfterReading)
                </div>
                <div>
                    @Html.LabelFor(m => m.NotifyEmail)
                    <br />
                    @Html.EditorFor(m => m.NotifyEmail)
                    @Html.ValidationMessageFor(m => m.NotifyEmail)
                </div>
                <div>
                    @Html.LabelFor(m => m.ReleaseDate)
                    <br />
                    @Html.EditorFor(m => m.ReleaseDate, new { @class = "ui-datepicker" })
                </div>
                <div>
                    @Html.LabelFor(m => m.LockDate)
                    <br />
                    @Html.EditorFor(m => m.LockDate)
                </div>
            </fieldset>
        </div>

        <div>
            <button id="btnMore" title="Advanced Options" class="ui-button" onclick="ShowMoreOptions();return false;">
                <span>(more)</span>
            </button>
            <button class="ui-button">Create a Key Id</button>
        </div>

        @*<div class="tabs">
            <ul>
                <li><a href="#online-key">Create Key Pair</a></li>
                <li><a href="#offline-key" title="(Advanced)">Import Public Key</a></li>
            </ul>
            <div id="online-key">
                
            </div>
            <div id="offline-key" class="red-box">
                <em>For super-secure offline mode, paste an RSA public key:</em>
                <br />
                <div>
                    @Html.LabelFor(m => m.PublicKey)
                    @Html.TextBoxFor(m => m.PublicKey)
                    @Html.ValidationMessageFor(m => m.PublicKey)
                </div>
                <div>
                    @Html.LabelFor(m => m.PrivateKeyHash)
                    @Html.TextBoxFor(m => m.PrivateKeyHash)
                    @Html.ValidationMessageFor(m => m.PrivateKeyHash)
                </div>
                <button class="ui-button">Import RSA Key</button>
            </div>
        </div>*@
    </div>

}

CryptAByte.WebUI/Views/Home/GetMessages.cshtml
@{ Layout = null;}
@model CryptAByte.WebUI.Models.GetMessagesModel
@using (Ajax.BeginForm("GetMessages", "Home", new AjaxOptions() { UpdateTargetId = "messageDetails", OnSuccess = "ShowMyMessages", OnFailure = "OnError" }))
{

    <div id="messageDetails"></div>


    <div id="get-messages" class="red-box">
        <h2>3: View Messages sent to a Key Id</h2>
        <div>@Html.LabelFor(m => m.KeyTokenIdentifier)
            @Html.TextBoxFor(m => m.KeyTokenIdentifier)
            @Html.ValidationMessageFor(m => m.KeyTokenIdentifier)
        </div>
        <div>
            @Html.LabelFor(m => m.Passphrase)
            @Html.PasswordFor(m => m.Passphrase)
            @Html.ValidationMessageFor(m => m.Passphrase)
        </div>
        <button class="ui-button">Show Messages</button>
    </div>

}

CryptAByte.WebUI/Views/Home/Index.cshtml
@{
    Page.Title = "CryptAByte: Secure, anonymous messaging and file sharing";
}

@*<h2>@ViewBag.Message</h2>*@

    
    <div id="instructions" class="ui-state-highlight ui-corner-all" style="display: none;">
            <p>
                <span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
                <h4>Send a message or file to the anonymous key below. Your message/file can only be
                    decrypted by a password for the private key matching the public key used to encrypt
                    this message.                    
                </h4>
        </div>
    

    <div class="content-left">
        @Html.Partial("CreateKey")
        @Html.Partial("SendMessage")
        @Html.Partial("GetMessages")
    </div>
    <div class="content-right">
        @Html.Partial("About-Home")
    </div>

CryptAByte.WebUI/Views/Home/MessagesDetail.cshtml
@using CryptAByte.Domain.KeyManager
@using CryptAByte.WebUI.Controllers
@model List<CryptAByte.Domain.KeyManager.Message>
@{Layout = null;}
@if (@Model.Count == 0)
{
    <strong>No messages sent to this key.</strong>    
}
else
{
    <ul>
        @foreach (Message message in @Model)
        {
            if (message.IsFile)
            {
            <li><strong>Sent @message.Created</strong>
                <pre class="red-box">Download <a href="#" onclick="javascript:GetFile('@message.TemporaryDownloadId');">@message.MessageData</a></pre>
            </li>    
            }
            else
            {
            <li><strong>Sent @message.Created</strong>
                <pre class="red-box">@message.MessageData</pre>
            </li>    
            }
        }
    </ul>
}
@if (Model.Any(m => m.IsFile))
{
    <p class="red-box">
        <em>Note: The link(s) above are valid for @HomeController.PasswordExpiresInSeconds seconds, after which the temporary download key will expire. </em>
    </p>
}

CryptAByte.WebUI/Views/Home/NewKeyDetails.cshtml
@{
    Layout = null;
    var URL = "https://" + Request.Url.Host + "#" + @Model.URI;
}
@model CryptAByte.Domain.KeyManager.CryptoKey
<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
    <p>
        <span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
        <label>Key URI:</label>
        <label><a target="_new" href="@URL">@URL</a></label>
        <p>
            Share this URL to securely attach files and messages to this key.
        </p>
</div>
<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
    <p>
        <div class="ui-widget">
            <div class="ui-state-error ui-corner-all">
                <p>
                    <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;">Passphrase:
                    </span>Passphrase: <strong>@ViewBag.Passphrase</strong>
            </div>
        </div>
        <p>
            Only someone with this passphrase can decrypt the messages and files sent to this
            address.
        </p>
    @*<p>
        You can use the offline app (coming soon) to encrypt the secret message offline,
        then upload them to this account.
    </p>*@
</div>

CryptAByte.WebUI/Views/Home/RequestKeys.cshtml
@model dynamic
<script type="text/javascript" src="../../Scripts/KeyManager.js"></script>
<div id="main">
    <div id="RequestKey">
        <h4>Create Request</h4>
        <input type="text" class="ui-widget" name="releaseDate" id="releaseDate" value=" " />
        <button id="btnCreateRequest">Create Request</button>
        <br />
        <label>Response</label>
        <textarea id="response" style="width: 800px;" cols="100" rows="10"></textarea>
        <br />
        <label>Token</label>
        <input type="text" name="name" value=" " id="token" style="width: 500px;" />
    </div>
    <div id="Message" class="ui-menu">
        <h4>Attach Message</h4>
        <textarea id="MessageText" cols="100"></textarea>
        <br />
        <button id="btnAttachMessage" class="ui-button ui-widget">
            Attach Message</button>
    </div>
    <div id="GetMessagesDiv">
        <h4>Get Messages</h4>
        <br />
        <button id="btnGetMessages" class="ui-button ui-widget">Get
            Messages</button>
    </div>
</div>

CryptAByte.WebUI/Views/Home/SendMessage.cshtml
@{ Layout = null;}
@model CryptAByte.WebUI.Models.SendMessageModel
@using (Html.BeginForm("SendMessage", "Home", FormMethod.Post, new { id = "SendMessageForm", enctype = "multipart/form-data" }))
{
    
    <div id="SendMessageStatus"></div>
    
    <div id="send-messages" class="blue-box">

        <h2>2: Send Messages &amp; Files to a Key Id</h2>
        <div>
            @Html.LabelFor(m => m.KeyToken)
            @Html.EditorFor(m => m.KeyToken)
            @Html.ValidationMessageFor(m => m.KeyToken)
        </div>
        <div>
            @Html.LabelFor(m => m.MessageText)
            @Html.TextAreaFor(m => m.MessageText, new { style = "width:90%; horiz-align:center;" })
            @Html.ValidationMessageFor(m => m.MessageText)
        </div>
        <div>
            @Html.LabelFor(m => m.UploadFile)
            <input type="file" name="UploadFile" id="UploadFile" />
            <div class="progress">
                <div class="bar"></div>
                <div class="percent">0%</div>
            </div>
        </div>

        <button class="ui-button">
            Send Message/File to Selected Key
        </button>
    </div>
}

CryptAByte.WebUI/Views/Home/ServiceInfo.cshtml
@model dynamic

@{
    ViewBag.Title = "API Information";
}

<h2>title</h2>

CryptAByte.WebUI/Views/Home/Subscribe.cshtml
@using CryptAByte.WebUI.Models
@model CryptAByte.WebUI.Models.ContactFormModel 


@*@using (Ajax.BeginForm("Subscribe", "Home", new AjaxOptions() { OnSuccess = "ShowMessageSent", OnFailure = "OnError" }))
{
    <div>

        <div>
            @Html.LabelFor(m=> m.Email)
            @Html.TextBoxFor(m=> m.Email)
            @Html.ValidationMessageFor(m=> m.Email)
        </div>
        <button class="ui-button">Subscribe for Updates</button>
    </div>
}*@


<!-- Begin MailChimp Signup Form -->
<link href="https://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="http://objectivismonline.us1.list-manage1.com/subscribe/post?u=591d9a0a5db8d52943e45d702&amp;id=e5da2e5ce7" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	<label for="mce-EMAIL">Subscribe to our mailing list</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
	<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->